spring.application.name=NovaWings
server.port=8080

# Mongodb Connect
spring.data.mongodb.uri=mongodb://localhost:27017/novawings

# JWT Configuration
app.jwt.secret=bXlTdXBlclNlY3JldEtleUZvck5vdmFXaW5nc0FwcGxpY2F0aW9uSldUMjAyNg==
app.jwt.expiration-ms=86400000

# Razorpay Configuration (use environment variables in production)
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SO0qUUeGYxxFkV}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:NWvnMmDg7kerPvAuLGjxp8cH}

# Email Configuration (Gmail SMTP)
ctual app password
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${EMAIL_USERNAME:meetchauhan9915@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:umqfyybagyrkcrgj}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Application Name
app.name=NovaWings