spring.application.name=NovaWings
server.port=8080

# Mongodb Connect
spring.data.mongodb.uri=mongodb://localhost:27017/novawings

# JWT Configuration
app.jwt.secret=bXlTdXBlclNlY3JldEtleUZvck5vdmFXaW5nc0FwcGxpY2F0aW9uSldUMjAyNg==
app.jwt.expiration-ms=86400000